volumes:
  ckan_storage:
  pg_data:
  solr_data:
  pip_cache:
  site_packages:

services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    networks:
      - webnet
      - ckannet
    depends_on:
      ckan:
        condition: service_healthy
    ports:
      - "0.0.0.0:${NGINX_SSLPORT_HOST}:${NGINX_SSLPORT}"
    restart: always

  # ckan-migrate:
  #   build:
  #     context: ckan/
  #     dockerfile: Dockerfile
  #     args:
  #       - TZ=${TZ}
  #   networks:
  #     - ckannet
  #     - dbnet
  #     - solrnet
  #     - redisnet
  #   env_file:
  #     - .env
  #   # environment:
  #   #   - SECRET_KEY=${CKAN___BEAKER__SESSION__SECRET}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   entrypoint: ["/usr/local/bin/ckan-entrypoint.sh"] # same as main container
  #   command: ["ckan", "db", "upgrade"]
  # volumes:
  #   - ckan_storage:/var/lib/ckan
  #   - pip_cache:/root/.cache/pip
  #   - site_packages:/usr/lib/python3.10/site-packages
  # restart: unless-stopped

  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    networks:
      - ckannet
      - dbnet
      - solrnet
      - redisnet
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
      # ckan-migrate:
      #   condition: service_completed_successfully
    volumes:
      - ckan_storage:/var/lib/ckan
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO",
          "/dev/null",
          "http://localhost:5000/api/action/status_show",
        ]
      interval: 60s
      timeout: 10s
      retries: 3

  datapusher:
    networks:
      - ckannet
      - dbnet
    image: ckan/ckan-base-datapusher:${DATAPUSHER_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8800"]
      interval: 60s
      timeout: 10s
      retries: 3

  db:
    build:
      context: postgresql/
    networks:
      - dbnet
      - webnet
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - CKAN_DB_USER
      - CKAN_DB_PASSWORD
      - CKAN_DB
      - DATASTORE_READONLY_USER
      - DATASTORE_READONLY_PASSWORD
      - DATASTORE_DB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]

  solr:
    networks:
      - solrnet
      - webnet
    # image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    build:
      context: ./solr
      dockerfile: Dockerfile
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]
    ports:
      - "8983:8983"

  redis:
    image: redis:${REDIS_VERSION}
    networks:
      - redisnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]

  rq-dashboard:
    build:
      context: ./rq-dashboard
      dockerfile: Dockerfile
    container_name: rq-dashboard
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379/1
      RQ_DASHBOARD_URL_PREFIX: /rq-dashboard
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    # volumes:
    #   - ../rq-dashboard:/rq-dashboard
    working_dir: /rq-dashboard
    command:
      - gunicorn
      - --bind
      - 0.0.0.0:9181
      - --workers
      - "2"
      - --threads
      - "2"
      - --timeout
      - "30"
      - --log-level
      - info
      - rq_dashboard.app:create_app()
    networks:
      - webnet
      - redisnet
    expose:
      - "9181"
    ports:
      - "9181:9181"
    depends_on:
      redis:
        condition: service_started

networks:
  webnet:
  ckannet:
  solrnet:
    internal: true
  dbnet:
    internal: true
  redisnet:
    internal: true
